spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT-8
    username: root
    password: 1111111111111111111111
